[package]
name = "plenora-storage-sftp"
description = "Plenora provider-neutral storage sftp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
async-trait.workspace = true
plenora-storage-core = { path = "../plenora-storage-core", version = "0.1.0" }
russh.workspace = true
russh-sftp.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true

[lints]
workspace = true
