[package]
name = "plenora-storage-ftp"
description = "Plenora provider-neutral storage ftp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
async-trait.workspace = true
plenora-storage-core = { path = "../plenora-storage-core", version = "0.2.1" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
suppaftp.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
rustls-native-certs.workspace = true
time.workspace = true
tokio.workspace = true

[lints]
workspace = true
