from dataclasses import dataclass
from os import PathLike
from typing import Any, Callable, Mapping
from ._native import CancellationToken as CancellationToken
from .types import DeleteResult, ListResult, ObjectInfo, OperationResult, PublicationPolicy, TestResult, TransferResult

__version__: str
__all__: list[str]
CredentialResolver = Callable[[str], Mapping[str, str]]

def version() -> str: ...
def cancellation_outcome(error: BaseException) -> OperationResult | PlenoraError | None: ...

class PlenoraError(Exception):
    code: str
    category: str
    phase: str
    remote_effect: str
    retry: dict[str, Any]
    provider: str | None
    details: dict[str, Any]
    message: str
    def __init__(self, document: Mapping[str, Any]) -> None: ...

class StorageError(PlenoraError): ...

@dataclass(frozen=True)
class EngineConfig:
    allow_insecure_http: bool = False
    allow_insecure_ftp: bool = False
    allow_private_network: bool = False
    allow_unverified_ssh: bool = False
    max_transfer_bytes: int = 1_073_741_824
    max_list_items: int = 10_000
    max_buffered_put_bytes: int = 67_108_864

@dataclass(frozen=True, repr=False)
class Connection:
    provider: str
    config_contract: str
    config: Mapping[str, Any]
    credential_ref: str

class Engine:
    def __init__(self, config: EngineConfig | None = None, *, credential_resolver: CredentialResolver | None = None, spool_uploads: bool = False) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, *_args: Any) -> None: ...
    def capabilities(self) -> dict[str, Any]: ...
    def test(self, connection: Connection, *, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> TestResult: ...
    def list(self, connection: Connection, *, prefix: str | None = None, cursor: str | None = None, max_items: int | None = None, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> ListResult: ...
    def stat(self, connection: Connection, key: str, *, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> ObjectInfo: ...
    def get(self, connection: Connection, key: str, output: str | PathLike[str], *, overwrite: bool, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> TransferResult: ...
    def put(self, connection: Connection, key: str, input: str | PathLike[str], *, overwrite: bool, publication_policy: PublicationPolicy, content_type: str | None = None, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> TransferResult: ...
    def copy(self, connection: Connection, source_key: str, destination_key: str, *, overwrite: bool, publication_policy: PublicationPolicy, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> ObjectInfo: ...
    def delete(self, connection: Connection, key: str, *, ignore_missing: bool, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> DeleteResult: ...

class AsyncEngine:
    def __init__(self, config: EngineConfig | None = None, *, credential_resolver: CredentialResolver | None = None, spool_uploads: bool = False) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    async def close(self) -> None: ...
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> AsyncEngine: ...
    async def __aexit__(self, *_args: Any) -> None: ...
    def capabilities(self) -> dict[str, Any]: ...
    async def test(self, connection: Connection, *, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> TestResult: ...
    async def list(self, connection: Connection, *, prefix: str | None = None, cursor: str | None = None, max_items: int | None = None, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> ListResult: ...
    async def stat(self, connection: Connection, key: str, *, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> ObjectInfo: ...
    async def get(self, connection: Connection, key: str, output: str | PathLike[str], *, overwrite: bool, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> TransferResult: ...
    async def put(self, connection: Connection, key: str, input: str | PathLike[str], *, overwrite: bool, publication_policy: PublicationPolicy, content_type: str | None = None, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> TransferResult: ...
    async def copy(self, connection: Connection, source_key: str, destination_key: str, *, overwrite: bool, publication_policy: PublicationPolicy, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> ObjectInfo: ...
    async def delete(self, connection: Connection, key: str, *, ignore_missing: bool, cancellation: CancellationToken | None = None, timeout_ms: int | None = None) -> DeleteResult: ...
