from typing import Callable, Mapping

__version__: str

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...

class Engine:
    def __init__(self, config: str, resolver: Callable[[str], dict[str, str]] | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def capabilities(self) -> str: ...
    def invoke(self, operation: str, connection: str, request: str, token: CancellationToken,
               timeout_ms: int | None = None) -> str: ...
