[global]
    server role = standalone server
    server min protocol = SMB3_00
    smb encrypt = required
    server signing = mandatory
    map to guest = Never
    load printers = no
    disable spoolss = yes
[storage]
    path = /data
    read only = no
    valid users = plenora
    follow symlinks = no
    wide links = no
